services:
  # MySQL
  db:
    build: ./docker/mysql
    container_name: db-container
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=hatalog
      - MYSQL_USER=hatalog
      - MYSQL_PASSWORD=hatalog
      - TZ=Asia/Tokyo
    ports:
      - '3306:3306'

  # Laravel + PHP + Node.js
  app:
    build: ./docker/php
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    container_name: app-container
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./laravel/hatalog:/var/www
    ports:
      - '3000:80'     # Laravel
      - '5173:5173'   # Vite (HMR)
    expose:
      - 9003
    depends_on:
      - db
    command: sh -c "npm install && npm run dev & apache2-foreground"

  # Adminer
  adminer:
    image: adminer:latest
    ports:
      - '8080:8080'
    depends_on:
      - db
